apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      volumes:
      - name: jenkins-home
        hostPath:
          path: /home/jenkins
      containers:
      - image: jenkins/jenkins:lts-jdk11
        name: jenkins
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
