apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: jenkins/jenkins:lts-jdk11
        name: jenkins
        volumeMounts:
        - mountPath: /var/jenkins_home5
          name: jenkins-home2
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
  volumeClaimTemplates:
  - metadata:
      name: jenkins-home2
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-storage"
      resources:
        requests:
          storage: 1Gi
