apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    name: jenkins-home
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts-jdk11
        name: jenkins
        ports:
        - containerPort: 8080        
        volumeMounts:
          - name: local-persistent-storage
            mountPath: /var/jenkins_home
      volumes:
        - name: local-persistent-storage
          persistentVolumeClaim:
            claimName: jenkins-home-pvc
      initContainers:
      - image: busybox
        name: init-jenkins-vol
        command: ['sh', '-c', 'chown -R 1000:1000 /mnt']
        volumeMounts:
          - name: local-persistent-storage
            mountPath: /mnt
